// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package nft_candy_machine

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// BurnSupplyV2 is the `burnSupplyV2` instruction.
type BurnSupplyV2 struct {
	PercentToBurn *uint8

	// [0] = [SIGNER] authority
	//
	// [1] = [WRITE] candyMachine
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewBurnSupplyV2InstructionBuilder creates a new `BurnSupplyV2` instruction builder.
func NewBurnSupplyV2InstructionBuilder() *BurnSupplyV2 {
	nd := &BurnSupplyV2{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetPercentToBurn sets the "percentToBurn" parameter.
func (inst *BurnSupplyV2) SetPercentToBurn(percentToBurn uint8) *BurnSupplyV2 {
	inst.PercentToBurn = &percentToBurn
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *BurnSupplyV2) SetAuthorityAccount(authority ag_solanago.PublicKey) *BurnSupplyV2 {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *BurnSupplyV2) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetCandyMachineAccount sets the "candyMachine" account.
func (inst *BurnSupplyV2) SetCandyMachineAccount(candyMachine ag_solanago.PublicKey) *BurnSupplyV2 {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(candyMachine).WRITE()
	return inst
}

// GetCandyMachineAccount gets the "candyMachine" account.
func (inst *BurnSupplyV2) GetCandyMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst BurnSupplyV2) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_BurnSupplyV2,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst BurnSupplyV2) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *BurnSupplyV2) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.PercentToBurn == nil {
			return errors.New("PercentToBurn parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.CandyMachine is not set")
		}
	}
	return nil
}

func (inst *BurnSupplyV2) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("BurnSupplyV2")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("PercentToBurn", *inst.PercentToBurn))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("candyMachine", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj BurnSupplyV2) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `PercentToBurn` param:
	err = encoder.Encode(obj.PercentToBurn)
	if err != nil {
		return err
	}
	return nil
}
func (obj *BurnSupplyV2) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `PercentToBurn`:
	err = decoder.Decode(&obj.PercentToBurn)
	if err != nil {
		return err
	}
	return nil
}

// NewBurnSupplyV2Instruction declares a new BurnSupplyV2 instruction with the provided parameters and accounts.
func NewBurnSupplyV2Instruction(
	// Parameters:
	percentToBurn uint8,
	// Accounts:
	authority ag_solanago.PublicKey,
	candyMachine ag_solanago.PublicKey) *BurnSupplyV2 {
	return NewBurnSupplyV2InstructionBuilder().
		SetPercentToBurn(percentToBurn).
		SetAuthorityAccount(authority).
		SetCandyMachineAccount(candyMachine)
}
