// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package nft_candy_machine

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// BurnSupply is the `burnSupply` instruction.
type BurnSupply struct {
	PercentToBurn *uint8

	// [0] = [SIGNER] authority
	//
	// [1] = [WRITE] candyMachine
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewBurnSupplyInstructionBuilder creates a new `BurnSupply` instruction builder.
func NewBurnSupplyInstructionBuilder() *BurnSupply {
	nd := &BurnSupply{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetPercentToBurn sets the "percentToBurn" parameter.
func (inst *BurnSupply) SetPercentToBurn(percentToBurn uint8) *BurnSupply {
	inst.PercentToBurn = &percentToBurn
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *BurnSupply) SetAuthorityAccount(authority ag_solanago.PublicKey) *BurnSupply {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *BurnSupply) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetCandyMachineAccount sets the "candyMachine" account.
func (inst *BurnSupply) SetCandyMachineAccount(candyMachine ag_solanago.PublicKey) *BurnSupply {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(candyMachine).WRITE()
	return inst
}

// GetCandyMachineAccount gets the "candyMachine" account.
func (inst *BurnSupply) GetCandyMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst BurnSupply) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_BurnSupply,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst BurnSupply) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *BurnSupply) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.PercentToBurn == nil {
			return errors.New("PercentToBurn parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.CandyMachine is not set")
		}
	}
	return nil
}

func (inst *BurnSupply) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("BurnSupply")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("PercentToBurn", *inst.PercentToBurn))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("candyMachine", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj BurnSupply) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `PercentToBurn` param:
	err = encoder.Encode(obj.PercentToBurn)
	if err != nil {
		return err
	}
	return nil
}
func (obj *BurnSupply) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `PercentToBurn`:
	err = decoder.Decode(&obj.PercentToBurn)
	if err != nil {
		return err
	}
	return nil
}

// NewBurnSupplyInstruction declares a new BurnSupply instruction with the provided parameters and accounts.
func NewBurnSupplyInstruction(
	// Parameters:
	percentToBurn uint8,
	// Accounts:
	authority ag_solanago.PublicKey,
	candyMachine ag_solanago.PublicKey) *BurnSupply {
	return NewBurnSupplyInstructionBuilder().
		SetPercentToBurn(percentToBurn).
		SetAuthorityAccount(authority).
		SetCandyMachineAccount(candyMachine)
}
