// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package nft_candy_machine

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetWhitelist is the `setWhitelist` instruction.
type SetWhitelist struct {
	Wl *WhitelistV2 `bin:"optional"`

	// [0] = [SIGNER] authority
	//
	// [1] = [WRITE] candyMachine
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetWhitelistInstructionBuilder creates a new `SetWhitelist` instruction builder.
func NewSetWhitelistInstructionBuilder() *SetWhitelist {
	nd := &SetWhitelist{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetWl sets the "wl" parameter.
func (inst *SetWhitelist) SetWl(wl WhitelistV2) *SetWhitelist {
	inst.Wl = &wl
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *SetWhitelist) SetAuthorityAccount(authority ag_solanago.PublicKey) *SetWhitelist {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *SetWhitelist) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetCandyMachineAccount sets the "candyMachine" account.
func (inst *SetWhitelist) SetCandyMachineAccount(candyMachine ag_solanago.PublicKey) *SetWhitelist {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(candyMachine).WRITE()
	return inst
}

// GetCandyMachineAccount gets the "candyMachine" account.
func (inst *SetWhitelist) GetCandyMachineAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetWhitelist) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetWhitelist,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetWhitelist) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetWhitelist) Validate() error {
	// Check whether all (required) parameters are set:
	{
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.CandyMachine is not set")
		}
	}
	return nil
}

func (inst *SetWhitelist) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetWhitelist")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Wl (OPT)", inst.Wl))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("   authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("candyMachine", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetWhitelist) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Wl` param (optional):
	{
		if obj.Wl == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Wl)
			if err != nil {
				return err
			}
		}
	}
	return nil
}
func (obj *SetWhitelist) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Wl` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.Wl)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// NewSetWhitelistInstruction declares a new SetWhitelist instruction with the provided parameters and accounts.
func NewSetWhitelistInstruction(
	// Parameters:
	wl WhitelistV2,
	// Accounts:
	authority ag_solanago.PublicKey,
	candyMachine ag_solanago.PublicKey) *SetWhitelist {
	return NewSetWhitelistInstructionBuilder().
		SetWl(wl).
		SetAuthorityAccount(authority).
		SetCandyMachineAccount(candyMachine)
}
